### ISSUE TITLE
Issue adding MySQL Data

### ISSUE THREAD

**Issue by RenAToSRL** [MichaelCade/project_pace#9]
Hey there,

I am running into an issue when trying to use the MySQL instance. 
After I run the container image to act as client, I get "I have no name @mysql-client", so that step seems to work. If I try to create 
a database, however, i get:

"mysql: Can't get stat of '/opt/bitnami/mysql/conf/bitnami/my_custom.cnf' (OS errno 2 - No such file or directory)"

![image](https://user-images.githubusercontent.com/65736921/141531999-cbaab6d7-27b7-4984-84fb-dab35d20ddc2.png)

I have not been able to find out what the issue is, perhaps there is a step required after installing mysql with helm/bitnami?

Thanks in advance for your time!

**Comment by MichaelCade** [comment]
Thanks for posting, I have just run through this on my Linux Desktop and WSL, I do not get the issue. 

Can you confirm you have set the environment variables with the below code? 
```

MYSQL_ROOT_PASSWORD=$(kubectl get secret --namespace ${APP_NAME} mysql-store -o jsonpath="{.data.mysql-root-password}" | base64 --decode)
MYSQL_HOST=mysql-store.${APP_NAME}.svc.cluster.local
MYSQL_EXEC="mysql -h ${MYSQL_HOST} -u root --password=${MYSQL_ROOT_PASSWORD} -DmyImportantData -t"
echo MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
```
I did have some issues on my laptop with the latest MySQL image that I am just checking now to make sure all is well and now working again, but it looks to be ok and think it was down to poor internet connectivity that was causing an issue.

**Comment by MichaelCade** [comment]
I just checked this and I think I reproduced your issue and it comes down to the environment variables posted above, please verify so that I can update the readme.

**Comment by RenAToSRL** [comment]
Hey there. I am indeed setting the variables correctly.

I believe the problem has to do with resource consumption, just launching the demo container gets me on 99%CPU and RAM (I'm on ubuntu on WSL 2.0). 

Using --memory='8g' when running minikube for the first time doesn't seem to help, however I believe I have made things better with some parameters on my .wslconfig file.

I will let you know if I have progress on this.

**Comment by RenAToSRL** [comment]
Hey there, updating you on where I am so far. The problem was related with resources, after creating a .wslfile and limiting the resources used by WSL 2.0 to around 10GB I could bypass the issue. I am copying the contents of my .wslfile below for anyone who has this problem:

```
[wsl2]
memory=10GB # Limits VM memory in WSL 2 
guiApplications=false
processors=4 # Makes the WSL 2 VM use 4 virtual processors
localhostForwarding=true # Boolean specifying if ports bound to wildcard or localhost in the WSL 2 VM should be connectable from the host via localhost:port.
```
This should not be needed if you run minikube with --memory='8g', but my installation was clearly ignoring that parameter for some reason.

I will now close this issue and create a different one for the problems I met moving forward lol.

**Comment by MichaelCade** [comment]
Thanks for following up with this.
